---
  - name: Ensure database is created
    become_user: postgres
    postgresql_db: name={{db.name}}

  - name: Ensure user has access to database
    become_user: postgres
    postgresql_user: db={{db.name}} name={{db.user}} password={{db.pass}} priv=ALL

  - name: Ensure user does not have unnecessary privilege
    become_user: postgres
    postgresql_user: name={{db.user}} role_attr_flags=NOSUPERUSER,NOCREATEDB

  - name: Ensure no other user can access the database
    become_user: postgres
    postgresql_privs: db={{db.name}} role=PUBLIC type=database priv=ALL state=absent

  - name: Enable Postgis extension if not exists
    become_user: postgres
    command: psql -d {{db.name}} -c "CREATE EXTENSION IF NOT EXISTS postgis;" 
    ignore_errors: yes
