---

 - name: Install django from repo
   become_user: djangoer
   pip: 
     virtualenv: '{{django.pyenv_dir}}'
     name: 'django=={{django.version}}'
     state: present 

 - name: Install app from repo
   become_user: djangoer
   pip: 
     virtualenv: '{{django.pyenv_dir}}'
     name: 'git+{{django.repo}}#egg=django-digdb'
     state: present
     extra_args: '--upgrade -e'

 - name: Check if project exists
   find: paths={{django.pyenv_dir}}/src/{{project}} patterns="manage.py"
   register: manage_py

 - name: Copy custom app
   become_user: djangoer
   when: custom_app
   copy: 
     src: 'custom_app/'
     dest: '{{django.pyenv_dir}}/src/{{project}}/{{custom_app.name}}'

 - name: Create django project
   become_user: djangoer
   command: "{{django.pyenv_dir}}/bin/django-admin.py startproject {{project}} {{django.pyenv_dir}}/src/{{project}}"
   when: manage_py.matched|int == 0

 - name: Install pip requirements for app
   become_user: djangoer
   pip:
     virtualenv: '{{django.pyenv_dir}}'
     requirements: '{{django.pyenv_dir}}/src/{{django.full_app}}/requirements.txt'

 - name: Copy settings.py template
   template: 
     src: 'etc/django/settings_before_schema.py' 
     dest: '{{django.pyenv_dir}}/src/{{project}}/{{project}}/settings.py'
     owner: djangoer
     mode: 0644

 - name: Copy static files folder
   become_user: djangoer
   copy: 
     src: 'static/'
     dest: '{{django.static_dir}}/digdb'

 - name: Collect static files
   become_user: djangoer
   django_manage:
     command: "collectstatic --noinput"
     app_path: "{{django.pyenv_dir}}/src/{{project}}"
     virtualenv: "{{django.pyenv_dir}}"

 - name: Copy jinja2 env fix
   become_user: djangoer
   copy: 
     src: 'jinja2_env.py'
     dest: '{{django.pyenv_dir}}/src/{{project}}/{{project}}'

 - name: Copy configuration json
   become_user: djangoer
   copy:
     src: 'digdb.json'
     dest: '{{django.pyenv_dir}}/src/{{project}}'

 - name: Copy translations file
   become_user: djangoer
   copy: 
     src: 'locale/'
     dest: '{{django.locale_dir}}'

 - name: Compile translation messages
   become_user: djangoer
   command: "{{django.pyenv_dir}}/bin/django-admin.py compilemessages"
   args:
     chdir: "{{django.default_dir}}"

 - name: Copy photos
   become_user: djangoer
   copy:
     src: 'photos/'
     dest: '{{django.uploads_dir}}'

