---
  
 - name: Install basic development libraries and utilities
   apt: pkg={{item}} state=latest
   with_items:
   - build-essential
   - python-dev
   - python-doc
   - python-virtualenv
   - python-setuptools
   - libxslt1-dev
   - libxml2-dev
   - gettext

 - name: Install compression/decompression libraries and utilities
   apt: pkg={{item}} state=latest
   with_items:
   - unzip
   - bzip2
   - p7zip-full
   - zlib1g-dev
 
 - name: Install database client libraries and utilities
   apt: pkg={{item}} state=latest
   with_items:
   - libpq5
   - libpq-dev

 - name: Install Apache2 webserver
   apt: pkg={{item}} state=latest
   with_items:
   - apache2
   - libapache2-mod-wsgi

 - name: Install pyopenssl
   pip:
     name: pyopenssl
     state: present
