---

 - name: Install django from repo
   become_user: djangoer
   pip: 
     virtualenv: '{{django.pyenv_dir}}'
     name: 'django=={{django.version}}'
     state: present
     #extra_args: '--upgrade -e'

 - name: Copy create super user template
   template:
     src: 'etc/django/createsuperuser.py'
     dest: "{{django.pyenv_dir}}/src/{{project}}/initadmin.py"
     owner: djangoer

 - name: Create default superuser
   become_user: djangoer
   ignore_errors: yes
   django_manage:
     command: "initadmin {{django.admin.user}} {{django.admin.email}} {{django.admin.pass}}"
     app_path: "{{django.pyenv_dir}}/src/{{project}}"
     virtualenv: "{{django.pyenv_dir}}"
