---

 - include: install-apt-packages.yml

 - include: configure-db.yml
 
 - include: create-env.yml

 - include: install-app.yml

 - include: init-schemata.yml

 - include: backup.yml

 - include: serve-with-apache2-wsgi.yml
   when: django.serve.use == 'apache2-mod-wsgi'

 - include: serve-development.yml
   when: django.serve.use == 'develop'

 - file: path=/etc/ansible/facts.d state=directory mode=0775 

