---

 # Create base directories, install Python virtual environment
 
 # Install Django and requirements 

 - include: install-apt-packages.yml
 - include: create-env.yml
 - include: configure-db.yml
 - include: install-django.yml
 - include: install-app.yml
 - include: init-schemata.yml
   #- include: init-app.yml
#   tags: ['install']

 # Configure Django
 
# - include: configure-django.yml 
#   tags: ['configure']

 # Initialize database (create tables from model)

# - include: init-ckan-db.yml
#   tags: ['init-db']

 # Initialize users. 
  
# - include: create-ckan-users.yml
#   tags: ['create-users']

 # Serve WSGI application
 
# - name: Check if given deploy method is compatible with debug mode
#   assert: 
#     that: 
     # The debug middleware not usable under Apache2 (either as proxy or as wsgi server)
#     - (not ckan.debug) or ckan.serve.use == 'paster'
#   tags: ['deploy']
 
# - include: clean-serve-with-paster.yml
#   when: present_ckan and (present_ckan.serve.use == 'paster')
#   tags: ['deploy']
 
# - include: clean-serve-with-apache2-proxy.yml
#   when: present_ckan and (present_ckan.serve.use == 'apache2/paster')
#   tags: ['deploy']


# - include: clean-serve-with-apache2-wsgi.yml
#   when: present_ckan and (present_ckan.serve.use == 'apache2-mod-wsgi')
#   tags: ['deploy']
 
 # NOTE This is because we want to short-circuit outgoing HTTP traffic to (one of) 
 # our names. But, of course, it shadows these actual names (which typically are
 # the virtual names of our frontend proxy).
# - name: Ensure our names are always resolved to a local address
#   lineinfile:
#     dest: /etc/hosts
#     line: '127.0.100.1 {{item}}'
#     insertafter: EOF
#   with_items: '{{[ckan.serve.name] + ckan.serve.name_aliases}}' 
#   tags: ['deploy']

# - include: serve-with-paster.yml
#   when: ckan.serve.use == 'paster'
#   tags: ['deploy']
 
# - include: serve-with-apache2-proxy.yml
#   when: ckan.serve.use == 'apache2/paster'
#   tags: ['deploy']


 - include: serve-with-apache2-wsgi.yml
   when: django.serve.use == 'apache2-mod-wsgi'
   tags: ['deploy']

 - include: serve-development.yml
   when: django.serve.use == 'develop'
   tags: ['deploy']

 # Dump current configuration

 - file: path=/etc/ansible/facts.d state=directory mode=0775 
   tags: ['dump-facts']
 
# - name: Dump current configuration as facts
#   copy: 
#     content: '{{item.value| to_nice_json}}'
#     dest: '/etc/ansible/facts.d/{{item.key}}.fact'
#     mode: 0640
#   with_dict:
#     ckan: '{{ckan}}'
#     ckanext: '{{ckanext}}'
#   tags: ['dump-facts']

